module.exports.descriptors = [
    'Forest',
    'Lake',
    'Mountain',
    'Rusty',
    'Dusty',
    'Sky',
    'Sea',
    'Redwood',
    'Silent',
    'Windy',
    'Cascade',
    'Sandy',
    'Diamond',
    'Red',
    'Blue',
    'Grizzly',
    'Ancient',
]
module.exports.places = [
    'Flats',
    'Rancho',
    'Horse Camp',
    'Vilage',
    'Farm',
    'Camp',
    'Cliffs',
    'Disapereed Camp ',
    'Pond',
    'Hunting Camp',
    'Spring',
    'Bay',
    'Mule',
    'Hollow',
]